version: '2'
services:
    web:
        build:
            context: ./
            dockerfile: web.docker
        volumes:
            - ./:/var/www
        links:
            - app
        ports:
            - "80:80"
    app:
        build:
            context: ./
            dockerfile: app.docker
        volumes:
            - ./:/var/www
        links:
            - database
            - cache
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=172.19.0.3"
            - "REDIS_PORT=6379"
            - "REDIS_HOST=cache"
    database:
        image: mysql:latest
        environment:
            - "MYSQL_DATABASE=myblog"
            - "MYSQL_USER=root"
            - "MYSQL_PASSWORD=secret"
            - "MYSQL_ROOT_PASSWORD=secret"
        ports:
            - "3306:3306"
    cache:
        image: redis:3.0
        ports:
            - "63791:6379"